name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x     # most up-to-date python version

    - name: Install packages
      run: make install         # install command in the Makefile

    - name: Lint
      run: make lint

    - name: Format Black
      run: make format
      
    - name: Run tests
      run: make test
